
INSERT INTO `cartas` (`id`, `tipo`, `carta`) VALUES
(8, 'poker', '../pokercards/2_of_spades.png'),
(7, 'poker', '../pokercards/2_of_hearts.png'),
(6, 'poker', '../pokercards/2_of_diamonds.png'),
(5, 'poker', '../pokercards/2_of_clubs.png'),
(9, 'poker', '../pokercards/3_of_clubs.png'),
(10, 'poker', '../pokercards/3_of_diamonds.png'),
(11, 'poker', '../pokercards/3_of_hearts.png'),
(12, 'poker', '../pokercards/3_of_spades.png'),
(13, 'poker', '../pokercards/4_of_clubs.png'),
(14, 'poker', '../pokercards/4_of_diamonds.png'),
(15, 'poker', '../pokercards/4_of_hearts.png'),
(16, 'poker', '../pokercards/4_of_spades.png'),
(17, 'poker', '../pokercards/5_of_clubs.png'),
(18, 'poker', '../pokercards/5_of_diamonds.png'),
(19, 'poker', '../pokercards/5_of_hearts.png'),
(29, 'poker', '../pokercards/8_of_clubs.png'),
(30, 'poker', '../pokercards/8_of_diamonds.png'),
(50, 'poker', '../pokercards/jack_of_hearts.png'),
(51, 'poker', '../pokercards/jack_of_hearts2.png'),
(122, 'snoopy', '../cartasSnoopy/snopy_music'),
(121, 'snoopy', '../cartasSnoopy/snoopy_totoro'),
(120, 'snoopy', '../cartasSnoopy/snoopy_rainbow'),
(119, 'snoopy', '../cartasSnoopy/snoopy_moon'),
(118, 'snoopy', '../cartasSnoopy/snoopy_japan'),
(117, 'snoopy', '../cartasSnoopy/snoopy_hippie'),
(116, 'snoopy', '../cartasSnoopy/Snoopy'),
(115, 'snoopy', '../cartasSnoopy/descarga (18)'),
(113, 'snoopy', '../cartasSnoopy/descarga (16)'),
(114, 'snoopy', '../cartasSnoopy/descarga (17)'),
(111, 'snoopy', '../cartasSnoopy/descarga (14)'),
(112, 'snoopy', '../cartasSnoopy/descarga (15)'),
(109, 'snoopy', '../cartasSnoopy/descarga (12)'),
(110, 'snoopy', '../cartasSnoopy/descarga (13)'),
(108, 'snoopy', '../cartasSnoopy/descarga (11)'),
(107, 'snoopy', '../cartasSnoopy/descarga (10)'),
(106, 'snoopy', '../cartasSnoopy/descarga (9)'),
(123, 'avion', '../cartasaviones/an-225.jpeg'),
(124, 'avion', '../cartasaviones/avion.jpg'),
(125, 'avion', '../cartasaviones/b747-8.jpg'),
(126, 'avion', '../cartasaviones/b767-300f.jpg'),
(127, 'avion', '../cartasaviones/b777x.webp'),
(128, 'avion', '../cartasaviones/beluga-xl.jpg'),
(129, 'avion', '../cartasaviones/c-5m.jpg'),
(130, 'avion', '../cartasaviones/c-17.jpg'),
(131, 'avion', '../cartasaviones/ilyushin-il-96.jpg'),
(132, 'avion', '../cartasaviones/image-4-1-1200x857.jpg'),
(133, 'avion', '../cartasaviones/image-4-2-1200x796.jpg'),
(134, 'avion', '../cartasaviones/image-4-3.jpg'),
(135, 'avion', '../cartasaviones/J-20-Mighty-Dragon.jpg'),
(136, 'avion', '../cartasaviones/l-1011-100.jpg'),
(137, 'avion', '../cartasaviones/stratolaunch-roc.jpg'),
(250, 'argentina', '../cartasArgentina/postalAvestruz'),
(251, 'argentina', '../cartasArgentina/worldcup'),
(252, 'avion', '../cartasaviones/bombardier.jpg'),
(249, 'argentina', '../cartasArgentina/postal'),
(248, 'argentina', '../cartasArgentina/pajaro'),
(247, 'argentina', '../cartasArgentina/mate'),
(243, 'argentina', '../cartasArgentina/album'),
(244, 'argentina', '../cartasArgentina/animal'),
(245, 'argentina', '../cartasArgentina/Argentina'),
(246, 'argentina', '../cartasArgentina/Fitz'),
(242, 'argentina', '../cartasArgentina/(pilardibujito)'),
(241, 'argentina', '../cartasArgentina/(11)'),
(240, 'argentina', '../cartasArgentina/(10)'),
(239, 'argentina', '../cartasArgentina/(9)'),
(238, 'argentina', '../cartasArgentina/(8)'),
(237, 'argentina', '../cartasArgentina/(7)'),
(236, 'argentina', '../cartasArgentina/(6)'),
(235, 'argentina', '../cartasArgentina/(5)'),
(234, 'argentina', '../cartasArgentina/(4)'),
(233, 'argentina', '../cartasArgentina/(3)');
COMMIT;